# Generated by Django 5.1.6 on 2025-02-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
